backend:
  name: git-gateway
  # name: github
  # repo: Landlord-Tech/opp-landing-page
  # branch: dev

#publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: category, label: Category }
      - { name: excerpt, label: Excerpt, widget: text, pattern: [
              "^.{150,500}$",
              "The Excerpt should contain from 150
              to 500 characters.",
            ] }
      - { name: heroHeading, label: Hero heading }
      - { name: heroImg, label: Hero image, widget: image }
      - { name: body, label: Body, widget: markdown }
      - {
          name: social,
          label: Social section,
          widget: boolean,
          required: false,
        }
      - label: Promo section
        name: promoSection
        widget: object
        fields:
          - { name: promoTitle, label: Promo section title, required: false }
          - {
              name: promoText,
              label: Promo section text,
              widget: text,
              required: false,
            }
          - { name: promoBtn, label: Promo section button, required: false }
          - {
              name: promoBtnUrl,
              label: Promo section button url,
              required: false,
            }
          - {
              name: promo,
              label: Promo section,
              widget: boolean,
              required: false,
            }

  - name: faq
    label: faq
    folder: faq
    preview_path: /
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description, widget: text }
      - { name: heroHeading, label: Hero Heading }
      - { name: heroSubhead, label: Hero Subhead }
      - { name: faqHeading, label: FAQ Heading }
      - name: faqList
        label: FAQ List
        widget: list
        fields:
          - { name: faqQuestion, label: FAQ question }
          - { name: faqAnswer, label: FAQ answer, widget: markdown }

  - name: blogList
    label: blogList
    folder: blogList
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description, widget: text }
      - { name: heroHeading, label: Hero heading }
      - { name: heroText, label: Hero text }
      - { name: heroImg, label: Hero image, widget: image }

  - name: homepage
    label: homepage
    folder: homepage
    preview_path: /
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description, widget: text }
      - { name: heroHeading, label: Hero heading }
      - { name: heroText, label: Hero text, widget: text }
      - { name: heroBtn, label: Hero button }
      - { name: heroBtnUrl, label: Hero button url }
      - { name: heroImg, label: Hero image, widget: image }
      - { name: sec1Heading, label: Section 1 heading }
      - { name: sec1Text, label: Section 1 text, widget: text }
      - { name: sec1Img, label: Section 1 image, widget: image }
      - { name: sec2Heading, label: Section 2 heading }
      - { name: sec2Img, label: Section 2 image, widget: image }
      - { name: sec2Btn, label: Section 2 Button }
      - { name: sec2BtnUrl, label: Section 2 Button url }
      - label: Section 2 List
        name: sec2List
        widget: list
        fields:
          - { label: List item, name: item }

  - name: notFound
    label: notFound
    folder: notFound
    preview_path: "404"
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: heroHeading, label: Hero heading }
      - { name: heroText, label: Hero text, widget: text }
      - { name: primaryBtn, label: Primary Button }
      - { name: secondaryBtn, label: Secondary Button }
      - { name: heroImg, label: Hero image, widget: image }

  - name: contact
    label: contact
    folder: contact
    preview_path: contact-us
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: heroHeading, label: Hero heading }
      - { name: heroText, label: Hero text, widget: text }
      - { name: sec1Heading, label: Contact heading }
      - label: Contact List
        name: contactList
        widget: list
        fields:
          - name: ContactItem
            label: Contact Field
            widget: list
            field: { name: line, label: Line, widget: string }
          - label: Contact icon
            name: icon
            widget: select
            options: [phone, cellphone, email, fax, skype, location]

  - name: footer
    label: Footer
    folder: footer
    preview_path: footer
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - label: Column 1 List
        name: col1List
        widget: list
        fields:
          - name: addressList
            label: Address list
            widget: list
            field: { name: line, label: Line, widget: string }
          - label: Icon
            name: icon
            widget: select
            options: [phone, cellphone, email, fax, skype, location]

      - { name: col2Title, label: Column 2 Title }
      - { name: col2TitleURL, label: Column 2 Title URL, required: false }
      - name: col2List
        label: Column 2 List
        widget: list
        fields:
          - { name: listItem, label: Column 2 Text }
          - { name: listItemUrl, label: Column 2 URL }
      - { name: col3Title, label: Column 3 Title }
      - { name: col3TitleURL, label: Column 3 Title URL, required: false }
      - name: col3List
        label: Column 3 List
        widget: list
        fields:
          - { name: listItem, label: QColumn 3 Text }
          - { name: listItemUrl, required: false, label: Column 3 URL }
          - label: Icon
            name: icon
            widget: select
            options: [phone, cellphone, email, fax, skype, location]
      - { name: col4Title, label: Column 4 Title }
      - { name: col4TitleURL, label: Column 4 Title URL, required: false }
      - name: col4List
        label: Column 4 List
        widget: list
        fields:
          - { name: listItem, label: QColumn 4 Text }
          - { name: listItemUrl, label: Column 4 URL }

  - name: termsAndConditions
    label: terms and conditions
    folder: termsAndConditions
    preview_path: terms-and-conditions
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: heroHeading, label: Hero title }
      - { name: body, label: Content, widget: markdown }

  - name: privacyPolicy
    label: privacy policy
    folder: privacyPolicy
    preview_path: privacy-policy
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: heroHeading, label: Hero title }
      - { name: body, label: Content, widget: markdown }

  - name: header
    label: header
    folder: header
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: hidden }
      - { name: primaryBtn, label: Primary button }
      - { name: primaryBtnUrl, label: Primary button url }
      - { name: secondaryBtn, label: Secondary button }
      - { name: secondaryBtnUrl, label: Secondary button url }
